//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblegitimler
    {
        public int id { get; set; }
        public string baslik { get; set; }
        public string altbaslik1 { get; set; }
        public string altbaslik2 { get; set; }
        public string gno { get; set; }
        public string tarih { get; set; }
    }
}
